I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 754, in script
    python:
  File "game/script.rpy", line 850, in <module>
    msg = chatgpt.completion(messages)
Exception: Error: 405, <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 754, in script
    python:
  File "/Library/Afolder/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Library/Afolder/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 850, in <module>
    msg = chatgpt.completion(messages)
  File "python-packages/chatgpt/__init__.py", line 38, in completion
Exception: Error: 405, <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>


macOS-14.2-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Amadeus 1.4.2
Sat Dec 16 15:23:10 2023
