I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 303, in script
    python:
  File "game/script.rpy", line 345, in <module>
    renpy.show("hito_kotoba2",at_list=["text"])
TypeError: 'str' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 303, in script
    python:
  File "/Library/Afolder/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Library/Afolder/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 345, in <module>
    renpy.show("hito_kotoba2",at_list=["text"])
  File "/Library/Afolder/renpy-8.1.3-sdk/renpy/exports.py", line 745, in show
    img = i(img) # type: ignore
TypeError: 'str' object is not callable

macOS-14.1.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Amadeus 1.2
Thu Nov  9 19:14:00 2023
